# Generated by Django 4.2.7 on 2025-06-18 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='responses',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
