# Generated by Django 4.2.7 on 2025-06-30 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_student_responses'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='college_id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
