# Generated by Django 4.2.7 on 2025-07-02 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_college_college_id_question_question_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='college_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_id',
            field=models.CharField(default=2, max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='RecommendationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_group_name', models.CharField(max_length=255)),
                ('num_recommendations', models.PositiveIntegerField(default=3)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.college')),
            ],
        ),
    ]
