# Generated by Django 4.2.7 on 2025-07-03 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_student_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
