# Generated by Django 4.2.7 on 2025-07-03 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_question_question_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('college', 'question_id')},
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('college', 'student_id')},
        ),
    ]
