# Generated by Django 4.2.7 on 2025-07-03 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_question_question_id_alter_student_student_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
