# Generated by Django 5.1.15 on 2025-12-16 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_college_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='question',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_id',
        ),
    ]
