# Generated by Django 5.2.6 on 2025-09-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_college_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='recommendation_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='recommendation_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default=None, max_length=10, null=True),
        ),
    ]
